[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#000000"
background = "#ffffff"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#525252"
background = "#ffffff"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#7c7c7c"
green = "#8b8b8b"
yellow = "#a0a0a0"
blue = "#686868"
magenta = "#747474"
cyan = "#868686"
white = "#b9b9b9"

[colors.bright]
black = "#525252"
red = "#7c7c7c"
green = "#8b8b8b"
yellow = "#a0a0a0"
blue = "#686868"
magenta = "#747474"
cyan = "#868686"
white = "#ffffff"

[colors.dim]
black = "#ffffff"
red = "#7c7c7c"
green = "#8b8b8b"
yellow = "#a0a0a0"
blue = "#686868"
magenta = "#747474"
cyan = "#868686"
white = "#525252"
